import { Injectable } from "@nestjs/common";
import { User } from "../interfaces/user.interface";
import { UserAbstractService } from './abstract/user-abstract.service';

@Injectable()
export class UserService {
  constructor(
    private readonly userAbstractService: UserAbstractService
  ){}

  async findAll() {
    const userAbstract = await this.userAbstractService.findAll();

    const userDto = userAbstract.map<User>(user => ({
      id: user.codigo,
      id_user_status: user.cdg_est_usuario,
      id_user_level: user.cdg_nvl_usuario,
      id_user_type: user.cdg_tpo_usuario,
      id_legal_person: user.cdg_prs_juridica,
      id_marital_status: user.cdg_est_civil,
      id_matrimonial_regime: user.cdg_rgm_matrimonial,
      id_country: user.cdg_pais,
      id_state: user.cdg_estado,
      id_municipality: user.cdg_municipio,
      id_city: user.cdg_ciudad,
      id_country_birth: user.cdg_pis_nacimiento,
      id_state_birth: user.cdg_est_nacimiento,
      id_municipality_birth: user.cdg_mnc_nacimiento,
      id_city_birth: user.cdg_cdd_nacimiento,
      id_origin: user.cdg_origen,
      id_nationality: user.cdg_nacionalidad,
      id_language: user.cdg_idioma,
      id_profession: user.cdg_profesion,
      id_commercial_activity: user.cdg_giro,
      id_national_ocupation: user.cdg_cdg_ncn_ocupacion,
      id_education_level: user.cdg_escolaridad,
      id_professional_title: user.cdg_ttl_profesional,
      id_gender: user.cdg_sexo,
      id_created_by: user.cdg_emp_alta,
      id_updated_by: user.cdg_emp_modificacion,
      id_deleted_by: user.cdg_emp_baja,
      id_satatus_provider_banorte: user.cdg_est_prv_banorte,
      id_satatus_employee_banorte: user.cdg_est_emp_banorte,
      id_public_office: user.cdg_crg_publico,
      id_company_size: user.cdg_tmn_empresa,
      id_resource_origin: user.cdg_org_recurso,
      id_resource_destination: user.cdg_dst_recurso,
      id_time_zone: user.idn_zna_horaria,
      personal_message: user.mns_personal,
      company_name: user.rzn_social,
      first_name: user.prm_nombre,
      second_name: user.sgn_nombre,
      first_last_name: user.apl_paterno,
      second_last_name: user.apl_materno,
      rfc: user.rfc,
      curp: user.curp,
      voter_key: user.clv_elector,
      fiel_serial_number: user.nmr_sre_fiel,
      taxpayer_identification_number: user.nmr_idn_fiscal,
      stp_CLABE: user.clb_int_stp,
      email: user.usuario,
      password: user.contrasena,
      nip: user.nip,
      wrong_attempt_counter: user.cnt_int_err_acceso,
      wrong_security_question_counter: user.cnt_int_err_prg_seguridad,
      total_PLD_risk_points: user.ttl_pnt_rsg_pld,
      profile_flag: user.prf_completo,
      user_file_flag: user.exp_completo,
      access: user.acceso,
      confirmed: user.confirmado,
      dtc_pld: user.dtc_pld,
      politically_exposed_person_flag: user.prs_plt_expuesta,
      has_secret_question: user.prg_sgr_respondida,
      signed_contract_flag: user.cnt_firmado,
      confirmation_key: user.llv_confirmacion,
      code_contract_sing: user.cdg_frm_contrato,
      email_flag: user.cdg_vld_crr_electronico,
      alt_email_flag: user.cdg_vld_crr_elc_alterno,
      avatar_image_url: user.url_img_avatar,
      monthly_income: user.ing_mensuales,
      amount_transactions_per_month: user.mnt_mxm_mns_transacciones,
      number_transactions_per_month: user.nmr_mxm_mns_transacciones,
      registration_latitude: user.ltt_ubc_registro,
      registration_longitude: user.lng_ubc_registro,
      last_location_latitude: user.ltt_ult_ubicacion,
      last_location_longitude: user.lng_ult_ubicacion,
      last_access_date: user.fch_ult_acceso,
      constitution_date: user.fch_constitucion,
      created_date: user.fch_alta,
      updated_date: user.fch_modificacion,
      deleted_date: user.fch_baja,
      id_economic_activity: user.cdg_act_economica,
      id_employee_validated_documentation: user.cdg_emp_vld_inf_documentacion,
      official_identification_number: user.nmr_idn_oficial,
      biometric_key: user.cnt_biometrica,
      operating_permit_flag: user.prm_operar,
      transactional_profile_flag: user.prf_trn_completo,
      validated_rfc: user.rfc_valido,
      validated_curp: user.crp_valido,
      in_blacklist: user.exs_lst_negras,
      general_info_flag: user.inf_gnr_completa,
      local_address_flag: user.dmc_rsd_registrado,
      correspondance_address_flag: user.dmc_crr_registrado,
      digital_level_2_info_flag: user.dcm_dgt_nvl_2_completa,
      digital_level_3_info_flag: user.dcm_dgt_nvl_3_completa,
      beneficiaries_registered_flag: user.bnf_registrados
    }));

    return userDto;
  }
}